### ISSUE TITLE
AttributeError: ElasticsearchSnapshotManager instance has no attribute 'sh'

### ISSUE THREAD

**Issue by nonstop99** [DomainGroupOSS/elasticsearch-snapshots#2]
Hi

I'm getting this error while trying to take a backup..

Traceback (most recent call last):
  File "es_backup.py", line 48, in <module>
    take_snapshot(options)
  File "es_backup.py", line 12, in take_snapshot
    sh = esm.sh
AttributeError: ElasticsearchSnapshotManager instance has no attribute 'sh'

i'm not sure if this is related to the facter requirement, i tried running

pip install factor

but this was the error when trying to install factor

Collecting facter
  Could not find a version that satisfies the requirement facter (from versions: )
No matching distribution found for facter

**Comment by gservat** [comment]
Hi @nonstop99,

Not sure if you still need help with this. This error message should be handled better, but in any case I've seen it happen when your cluster isn't in green state. The script waits for a while for it to be in green state and if it hits the timeout, this rather unhelpful error message shows up.

I've just pushed a change to `requirements.txt` so you should be able to do:

`pip install -r requirements.txt`
